version: '3'
services:
  unifi-video-controller:
    build: .
    container_name: unifi-video-controller
    ports:
      - 1935:1935
      - 6666:6666
      - 7004:7004
      - 7080:7080
      - 7442:7442
      - 7443:7443
      - 7444:7444
      - 7445:7445
      - 7446:7446
      - 7447:7447
    volumes:
      - /volume1/unifi-video:/var/lib/unifi-video
      - /volume1/unifi-video/videos:/var/lib/unifi-video/videos
    environment:
      - TZ=America/Chicago
      - PUID=1026
      - PGID=100
      - DEBUG=1
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
